export const showData = [
    {
        "show_id": "s1",
        "type": "TV Show",
        "title": "3%",
        "director": "",
        "cast": "JoÃ£o Miguel, Bianca Comparato, Michel Gomes, Rodolfo Valente, Vaneza Oliveira, Rafael Lozano, Viviane Porto, Mel Fronckowiak, Sergio Mamberti, ZezÃ© Motta, Celso Frateschi",
        "country": "Brazil",
        "date_added": "August 14, 2020",
        "release_year": "2020",
        "rating": "TV-MA",
        "duration": "4 Seasons",
        "listed_in": "International TV Shows, TV Dramas, TV Sci-Fi & Fantasy",
        "description": "In a future where the elite inhabit an island paradise far from the crowded slums, you get one chance to join the 3% saved from squalor."
    },
    {
        "show_id": "s2",
        "type": "Movie",
        "title": "7:19",
        "director": "Jorge Michel Grau",
        "cast": "DemiÃ¡n Bichir, HÃ©ctor Bonilla, Oscar Serrano, Azalia Ortiz, Octavio Michel, Carmen Beato",
        "country": "Mexico",
        "date_added": "December 23, 2016",
        "release_year": "2016",
        "rating": "TV-MA",
        "duration": "93 min",
        "listed_in": "Dramas, International Movies",
        "description": "After a devastating earthquake hits Mexico City, trapped survivors from all walks of life wait to be rescued while trying desperately to stay alive."
    },
    {
        "show_id": "s3",
        "type": "Movie",
        "title": "23:59",
        "director": "Gilbert Chan",
        "cast": "Tedd Chan, Stella Chung, Henley Hii, Lawrence Koh, Tommy Kuan, Josh Lai, Mark Lee, Susan Leong, Benjamin Lim",
        "country": "Singapore",
        "date_added": "December 20, 2018",
        "release_year": "2011",
        "rating": "R",
        "duration": "78 min",
        "listed_in": "Horror Movies, International Movies",
        "description": "When an army recruit is found dead, his fellow soldiers are forced to confront a terrifying secret that's haunting their jungle island training camp."
    },
    {
        "show_id": "s4",
        "type": "Movie",
        "title": "9",
        "director": "Shane Acker",
        "cast": "Elijah Wood, John C. Reilly, Jennifer Connelly, Christopher Plummer, Crispin Glover, Martin Landau, Fred Tatasciore, Alan Oppenheimer, Tom Kane",
        "country": "United States",
        "date_added": "November 16, 2017",
        "release_year": "2009",
        "rating": "PG-13",
        "duration": "80 min",
        "listed_in": "Action & Adventure, Independent Movies, Sci-Fi & Fantasy",
        "description": "In a postapocalyptic world, rag-doll robots hide in fear from dangerous machines out to exterminate them, until a brave newcomer joins the group."
    },
    {
        "show_id": "s5",
        "type": "Movie",
        "title": "21",
        "director": "Robert Luketic",
        "cast": "Jim Sturgess, Kevin Spacey, Kate Bosworth, Aaron Yoo, Liza Lapira, Jacob Pitts, Laurence Fishburne, Jack McGee, Josh Gad, Sam Golzari, Helen Carey, Jack Gilpin",
        "country": "United States",
        "date_added": "January 1, 2020",
        "release_year": "2008",
        "rating": "PG-13",
        "duration": "123 min",
        "listed_in": "Dramas",
        "description": "A brilliant group of students become card-counting experts with the intent of swindling millions out of Las Vegas casinos by playing blackjack."
    },
    {
        "show_id": "s6",
        "type": "TV Show",
        "title": "46",
        "director": "Serdar Akar",
        "cast": "Erdal BeÅikÃ§ioÄlu, Yasemin Allen, Melis Birkan, SaygÄ±n Soysal, Berkan Åal, Metin Belgin, AyÃ§a Eren, Selin UludoÄan, Ãzay Fecht, Suna YÄ±ldÄ±zoÄlu",
        "country": "Turkey",
        "date_added": "July 1, 2017",
        "release_year": "2016",
        "rating": "TV-MA",
        "duration": "1 Season",
        "listed_in": "International TV Shows, TV Dramas, TV Mysteries",
        "description": "A genetics professor experiments with a treatment for his comatose sister that blends medical and shamanic cures, but unlocks a shocking side effect."
    },
    {
        "show_id": "s7",
        "type": "Movie",
        "title": "122",
        "director": "Yasir Al Yasiri",
        "cast": "Amina Khalil, Ahmed Dawood, Tarek Lotfy, Ahmed El Fishawy, Mahmoud Hijazi, Jihane Khalil, Asmaa Galal, Tara Emad",
        "country": "Egypt",
        "date_added": "June 1, 2020",
        "release_year": "2019",
        "rating": "TV-MA",
        "duration": "95 min",
        "listed_in": "Horror Movies, International Movies",
        "description": "After an awful accident, a couple admitted to a grisly hospital are separated and must find each other to escape â before death finds them."
    },
    {
        "show_id": "s8",
        "type": "Movie",
        "title": "187",
        "director": "Kevin Reynolds",
        "cast": "Samuel L. Jackson, John Heard, Kelly Rowan, Clifton Collins Jr., Tony Plana",
        "country": "United States",
        "date_added": "November 1, 2019",
        "release_year": "1997",
        "rating": "R",
        "duration": "119 min",
        "listed_in": "Dramas",
        "description": "After one of his high school students attacks him, dedicated teacher Trevor Garfield grows weary of the gang warfare in the New York City school system and moves to California to teach there, thinking it must be a less hostile environment."
    },
    {
        "show_id": "s9",
        "type": "Movie",
        "title": "706",
        "director": "Shravan Kumar",
        "cast": "Divya Dutta, Atul Kulkarni, Mohan Agashe, Anupam Shyam, Raayo S. Bakhirta, Yashvit Sancheti, Greeva Kansara, Archan Trivedi, Rajiv Pathak",
        "country": "India",
        "date_added": "April 1, 2019",
        "release_year": "2019",
        "rating": "TV-14",
        "duration": "118 min",
        "listed_in": "Horror Movies, International Movies",
        "description": "When a doctor goes missing, his psychiatrist wife treats the bizarre medical condition of a psychic patient, who knows much more than he's leading on."
    },
    {
        "show_id": "s10",
        "type": "Movie",
        "title": "1920",
        "director": "Vikram Bhatt",
        "cast": "Rajneesh Duggal, Adah Sharma, Indraneil Sengupta, Anjori Alagh, Rajendranath Zutshi, Vipin Sharma, Amin Hajee, Shri Vallabh Vyas",
        "country": "India",
        "date_added": "December 15, 2017",
        "release_year": "2008",
        "rating": "TV-MA",
        "duration": "143 min",
        "listed_in": "Horror Movies, International Movies, Thrillers",
        "description": "An architect and his wife move into a castle that is slated to become a luxury hotel. But something inside is determined to stop the renovation."
    },
    {
        "show_id": "s11",
        "type": "Movie",
        "title": "1922",
        "director": "Zak Hilditch",
        "cast": "Thomas Jane, Molly Parker, Dylan Schmid, Kaitlyn Bernard, Bob Frazer, Brian d'Arcy James, Neal McDonough",
        "country": "United States",
        "date_added": "October 20, 2017",
        "release_year": "2017",
        "rating": "TV-MA",
        "duration": "103 min",
        "listed_in": "Dramas, Thrillers",
        "description": "A farmer pens a confession admitting to his wife's murder, but her death is just the beginning of a macabre tale. Based on Stephen King's novella."
    },
    {
        "show_id": "s12",
        "type": "TV Show",
        "title": "1983",
        "director": "",
        "cast": "Robert WiÄckiewicz, Maciej MusiaÅ, Michalina OlszaÅska, Andrzej Chyra, Clive Russell, Zofia WichÅacz, Edyta OlszÃ³wka, Mateusz KoÅciukiewicz, Ewa BÅaszczyk, Vu Le Hong, Tomasz WÅosok, Krzysztof Wach",
        "country": "Poland, United States",
        "date_added": "November 30, 2018",
        "release_year": "2018",
        "rating": "TV-MA",
        "duration": "1 Season",
        "listed_in": "Crime TV Shows, International TV Shows, TV Dramas",
        "description": "In this dark alt-history thriller, a naÃ¯ve law student and a world-weary detective uncover a conspiracy that has tyrannized Poland for decades."
    },
    {
        "show_id": "s13",
        "type": "TV Show",
        "title": "1994",
        "director": "Diego Enrique Osorno",
        "cast": "",
        "country": "Mexico",
        "date_added": "May 17, 2019",
        "release_year": "2019",
        "rating": "TV-MA",
        "duration": "1 Season",
        "listed_in": "Crime TV Shows, Docuseries, International TV Shows",
        "description": "Archival video and new interviews examine Mexican politics in 1994, a year marked by the rise of the EZLN and the assassination of Luis Donaldo Colosio."
    },
    {
        "show_id": "s14",
        "type": "Movie",
        "title": "2,215",
        "director": "Nottapon Boonprakob",
        "cast": "Artiwara Kongmalai",
        "country": "Thailand",
        "date_added": "March 1, 2019",
        "release_year": "2018",
        "rating": "TV-MA",
        "duration": "89 min",
        "listed_in": "Documentaries, International Movies, Sports Movies",
        "description": "This intimate documentary follows rock star Artiwara Kongmalai on his historic, 2,215-kilometer charity run across Thailand in 2017."
    },
    {
        "show_id": "s15",
        "type": "Movie",
        "title": "3022",
        "director": "John Suits",
        "cast": "Omar Epps, Kate Walsh, Miranda Cosgrove, Angus Macfadyen, Jorja Fox, Enver Gjokaj, Haaz Sleiman",
        "country": "United States",
        "date_added": "March 19, 2020",
        "release_year": "2019",
        "rating": "R",
        "duration": "91 min",
        "listed_in": "Independent Movies, Sci-Fi & Fantasy, Thrillers",
        "description": "Stranded when the Earth is suddenly destroyed in a mysterious cataclysm, the astronauts aboard a marooned space station slowly lose their minds."
    },
    {
        "show_id": "s16",
        "type": "Movie",
        "title": "Oct-01",
        "director": "Kunle Afolayan",
        "cast": "Sadiq Daba, David Bailie, Kayode Olaiya, Kehinde Bankole, Fabian Adeoye Lojede, Nick Rhys, Kunle Afolayan, Colin David Reese, Ibrahim Shatta, Femi Adebayo, Kanayo O. Kanayo, Lawrence Stubbings, Ademola Adedoyin",
        "country": "Nigeria",
        "date_added": "September 1, 2019",
        "release_year": "2014",
        "rating": "TV-14",
        "duration": "149 min",
        "listed_in": "Dramas, International Movies, Thrillers",
        "description": "Against the backdrop of Nigeria's looming independence from Britain, detective Danladi Waziri races to capture a killer terrorizing local women."
    },
    {
        "show_id": "s17",
        "type": "TV Show",
        "title": "Feb-09",
        "director": "",
        "cast": "Shahd El Yaseen, Shaila Sabt, Hala, Hanadi Al-Kandari, Salma Salem, Ibrahim Al-Harbi, Mahmoud Boushahri, Yousef Al Balushi, Ghorour, Abdullah Al-bloshi",
        "country": "",
        "date_added": "March 20, 2019",
        "release_year": "2018",
        "rating": "TV-14",
        "duration": "1 Season",
        "listed_in": "International TV Shows, TV Dramas",
        "description": "As a psychology professor faces Alzheimer's, his daughter and her three close female friends experience romance, marriage, heartbreak and tragedy."
    },
    {
        "show_id": "s18",
        "type": "Movie",
        "title": "22-Jul",
        "director": "Paul Greengrass",
        "cast": "Anders Danielsen Lie, Jon Ãigarden, Jonas Strand Gravli, Ola G. Furuseth, Maria Bock, ThorbjÃ¸rn Harr, Jaden Smith",
        "country": "Norway, Iceland, United States",
        "date_added": "October 10, 2018",
        "release_year": "2018",
        "rating": "R",
        "duration": "144 min",
        "listed_in": "Dramas, Thrillers",
        "description": "After devastating terror attacks in Norway, a young survivor, grieving families and the country rally for justice and healing. Based on a true story."
    },
    {
        "show_id": "s19",
        "type": "Movie",
        "title": "15-Aug",
        "director": "Swapnaneel Jayakar",
        "cast": "Rahul Pethe, Mrunmayee Deshpande, Adinath Kothare, Vaibhav Mangale, Jaywant Wadkar, Satish Pulekar, Naina Apte, Uday Tikekar",
        "country": "India",
        "date_added": "March 29, 2019",
        "release_year": "2019",
        "rating": "TV-14",
        "duration": "124 min",
        "listed_in": "Comedies, Dramas, Independent Movies",
        "description": "On India's Independence Day, a zany mishap in a Mumbai chawl disrupts a young love story while compelling the residents to unite in aid of a little boy."
    },
    {
        "show_id": "s20",
        "type": "Movie",
        "title": "'89",
        "director": "",
        "cast": "Lee Dixon, Ian Wright, Paul Merson",
        "country": "United Kingdom",
        "date_added": "May 16, 2018",
        "release_year": "2017",
        "rating": "TV-PG",
        "duration": "87 min",
        "listed_in": "Sports Movies",
        "description": "Mixing old footage with interviews, this is the story of Arsenal's improbable win versus Liverpool in the final moments of the 1989 championship game."
    },
    {
        "show_id": "s21",
        "type": "Movie",
        "title": "ââKuch Bheege Alfaaz",
        "director": "Onir",
        "cast": "Geetanjali Thapa, Zain Khan Durrani, Shray Rai Tiwari, Mona Ambegaonkar, Chandreyee Ghosh, Barun Chanda, Saheb Bhattacharjee, Shefali Chauhan",
        "country": "India",
        "date_added": "September 1, 2018",
        "release_year": "2018",
        "rating": "TV-14",
        "duration": "110 min",
        "listed_in": "Dramas, Independent Movies, International Movies",
        "description": "After accidentally connecting over the Internet, two strangers form a tight friendship â not knowing they already share a bond."
    },
    {
        "show_id": "s22",
        "type": "Movie",
        "title": "âGoli Soda 2",
        "director": "Vijay Milton",
        "cast": "Samuthirakani, Bharath Seeni, Vinoth, Esakki Barath, Chemban Vinod Jose, Gautham Menon, Krisha Kurup, Subiksha",
        "country": "India",
        "date_added": "September 15, 2018",
        "release_year": "2018",
        "rating": "TV-14",
        "duration": "128 min",
        "listed_in": "Action & Adventure, Dramas, International Movies",
        "description": "A taxi driver, a gangster and an athlete struggle to better their lives despite obstacles like crooked politicians, evil dons and caste barriers."
    },
    {
        "show_id": "s23",
        "type": "Movie",
        "title": "âMaj Rati ââKeteki",
        "director": "Santwana Bardoloi",
        "cast": "Adil Hussain, Shakil Imtiaz, Mahendra Rabha, Sulakshana Baruah, Rahul Gautam Sarma, Kulada Bhattacharjya, Indu Mohan Das, Moumita Talukdar",
        "country": "India",
        "date_added": "September 15, 2018",
        "release_year": "2017",
        "rating": "TV-14",
        "duration": "117 min",
        "listed_in": "Dramas, International Movies",
        "description": "A successful writer returns to the town that launched his career, encountering people who spark nostalgic, often painfully illuminating flashbacks."
    },
    {
        "show_id": "s24",
        "type": "Movie",
        "title": "âMayurakshi",
        "director": "Atanu Ghosh",
        "cast": "Soumitra Chatterjee, Prasenjit Chatterjee, Indrani Haldar, Sudipta Chakraborty, Suman Banerjee, Gargi Roychowdhury",
        "country": "India",
        "date_added": "September 15, 2018",
        "release_year": "2017",
        "rating": "TV-14",
        "duration": "100 min",
        "listed_in": "Dramas, International Movies",
        "description": "When a middle-aged divorcee returns to Kolkata to visit his ailing father, long-buried memories resurface, bringing new discoveries with them."
    },
    {
        "show_id": "s25",
        "type": "TV Show",
        "title": "âSAINT SEIYA: Knights of the Zodiac",
        "director": "",
        "cast": "Bryson Baugus, Emily Neves, Blake Shepard, Patrick Poole, Luci Christian, Adam Gibbs, Masakazu Morita, Fumiko Orikasa, Takahiro Sakurai, Hiroaki Miura, Satomi Sato, Katsuyuki Konishi",
        "country": "Japan",
        "date_added": "January 23, 2020",
        "release_year": "2020",
        "rating": "TV-14",
        "duration": "2 Seasons",
        "listed_in": "Anime Series, International TV Shows",
        "description": "Seiya and the Knights of the Zodiac rise again to protect the reincarnation of the goddess Athena, but a dark prophecy hangs over them all."
    },
    {
        "show_id": "s26",
        "type": "Movie",
        "title": "(T)ERROR",
        "director": "Lyric R. Cabral, David Felix Sutcliffe",
        "cast": "",
        "country": "United States",
        "date_added": "June 30, 2016",
        "release_year": "2015",
        "rating": "NR",
        "duration": "84 min",
        "listed_in": "Documentaries",
        "description": "This real-life look at FBI counterterrorism operations features access to both sides of a sting: the government informant and the radicalized target."
    },
    {
        "show_id": "s27",
        "type": "TV Show",
        "title": "(Un)Well",
        "director": "",
        "cast": "",
        "country": "United States",
        "date_added": "August 12, 2020",
        "release_year": "2020",
        "rating": "TV-MA",
        "duration": "1 Season",
        "listed_in": "Reality TV",
        "description": "This docuseries takes a deep dive into the lucrative wellness industry, which touts health and healing. But do the products live up to the promises?"
    },
    {
        "show_id": "s28",
        "type": "Movie",
        "title": "#Alive",
        "director": "Cho Il",
        "cast": "Yoo Ah-in, Park Shin-hye",
        "country": "South Korea",
        "date_added": "September 8, 2020",
        "release_year": "2020",
        "rating": "TV-MA",
        "duration": "99 min",
        "listed_in": "Horror Movies, International Movies, Thrillers",
        "description": "As a grisly virus rampages a city, a lone man stays locked inside his apartment, digitally cut off from seeking help and desperate to find a way out."
    },
    {
        "show_id": "s29",
        "type": "Movie",
        "title": "#AnneFrank - Parallel Stories",
        "director": "Sabina Fedeli, Anna Migotto",
        "cast": "Helen Mirren, Gengher Gatti",
        "country": "Italy",
        "date_added": "July 1, 2020",
        "release_year": "2019",
        "rating": "TV-14",
        "duration": "95 min",
        "listed_in": "Documentaries, International Movies",
        "description": "Through her diary, Anne Frank's story is retold alongside those of five Holocaust survivors in this poignant documentary from Oscar winner Helen Mirren."
    },
    {
        "show_id": "s30",
        "type": "TV Show",
        "title": "#blackAF",
        "director": "",
        "cast": "Kenya Barris, Rashida Jones, Iman Benson, Genneya Walton, Scarlet Spencer, Justin Claiborne, Ravi Cabot-Conyers",
        "country": "United States",
        "date_added": "April 17, 2020",
        "release_year": "2020",
        "rating": "TV-MA",
        "duration": "1 Season",
        "listed_in": "TV Comedies",
        "description": "Kenya Barris and his family navigate relationships, race and culture while grappling with their newfound success in this comedy series."
    },
    {
        "show_id": "s31",
        "type": "Movie",
        "title": "#cats_the_mewvie",
        "director": "Michael Margolis",
        "cast": "",
        "country": "Canada",
        "date_added": "February 5, 2020",
        "release_year": "2020",
        "rating": "TV-14",
        "duration": "90 min",
        "listed_in": "Documentaries, International Movies",
        "description": "This pawesome documentary explores how our feline friends became online icons, from the earliest text memes to the rise of celebrity cat influencers."
    },
    {
        "show_id": "s32",
        "type": "Movie",
        "title": "#FriendButMarried",
        "director": "Rako Prijanto",
        "cast": "Adipati Dolken, Vanesha Prescilla, Rendi Jhon, Beby Tsabina, Denira Wiraguna, Refal Hady, Diandra Agatha, Sari Nila",
        "country": "Indonesia",
        "date_added": "May 21, 2020",
        "release_year": "2018",
        "rating": "TV-G",
        "duration": "102 min",
        "listed_in": "Dramas, International Movies, Romantic Movies",
        "description": "Pining for his high school crush for years, a young man puts up his best efforts to move out of the friend zone until she reveals she's getting married."
    },
    {
        "show_id": "s33",
        "type": "Movie",
        "title": "#FriendButMarried 2",
        "director": "Rako Prijanto",
        "cast": "Adipati Dolken, Mawar de Jongh, Sari Nila, Vonny Cornellya, Clay Gribble, Ivan Leonardy, Sarah Sechan, Jourdy Pranata",
        "country": "Indonesia",
        "date_added": "June 28, 2020",
        "release_year": "2020",
        "rating": "TV-G",
        "duration": "104 min",
        "listed_in": "Dramas, International Movies, Romantic Movies",
        "description": "As Ayu and Ditto finally transition from best friends to newlyweds, a quick pregnancy creates uncertainty for the future of their young marriage."
    },
    {
        "show_id": "s34",
        "type": "Movie",
        "title": "#realityhigh",
        "director": "Fernando Lebrija",
        "cast": "Nesta Cooper, Kate Walsh, John Michael Higgins, Keith Powers, Alicia Sanz, Jake Borelli, Kid Ink, Yousef Erakat, Rebekah Graf, Anne Winters, Peter Gilroy, Patrick Davis",
        "country": "United States",
        "date_added": "September 8, 2017",
        "release_year": "2017",
        "rating": "TV-14",
        "duration": "99 min",
        "listed_in": "Comedies",
        "description": "When nerdy high schooler Dani finally attracts the interest of her longtime crush, she lands in the cross hairs of his ex, a social media celebrity."
    },
    {
        "show_id": "s35",
        "type": "Movie",
        "title": "#Roxy",
        "director": "Michael Kennedy",
        "cast": "Jake Short, Sarah Fisher, Booboo Stewart, Danny Trejo, Pippa Mackie, Jake Smith, Patricia Zentilli, Carter Thicke",
        "country": "Canada",
        "date_added": "April 10, 2019",
        "release_year": "2018",
        "rating": "TV-14",
        "duration": "105 min",
        "listed_in": "Comedies, Romantic Movies",
        "description": "A teenage hacker with a huge nose helps a cool kid woo a girl that heâs secretly in love with."
    },
    {
        "show_id": "s36",
        "type": "Movie",
        "title": "#Rucker50",
        "director": "Robert McCullough Jr.",
        "cast": "",
        "country": "United States",
        "date_added": "December 1, 2016",
        "release_year": "2016",
        "rating": "TV-PG",
        "duration": "56 min",
        "listed_in": "Documentaries, Sports Movies",
        "description": "This documentary celebrates the 50th anniversary of the Harlem sports program that has inspired countless city kids to become pro basketball players."
    },
    {
        "show_id": "s37",
        "type": "Movie",
        "title": "#Selfie",
        "director": "Cristina Jacob",
        "cast": "Flavia Hojda, Crina Semciuc, Olimpia Melinte, Levent Sali, Vlad Logigan, Alex Calin, Alina Chivulescu, Razvan Vasilescu",
        "country": "Romania",
        "date_added": "June 1, 2019",
        "release_year": "2014",
        "rating": "TV-MA",
        "duration": "125 min",
        "listed_in": "Comedies, Dramas, International Movies",
        "description": "Two days before their final exams, three teen girls make a seaside getaway to end their adolescence with a bang."
    },
    {
        "show_id": "s38",
        "type": "Movie",
        "title": "#Selfie 69",
        "director": "Cristina Jacob",
        "cast": "Maia Morgenstern, Olimpia Melinte, Crina Semciuc, Flavia Hojda, Maria Dinulescu, Alex Calin, Vlad Logigan, Levent Sali, Silvia Busuioc, Mihaela Mihut",
        "country": "Romania",
        "date_added": "June 1, 2019",
        "release_year": "2016",
        "rating": "TV-MA",
        "duration": "119 min",
        "listed_in": "Comedies, Dramas, International Movies",
        "description": "After a painful breakup, a trio of party-loving friends makes a bet: who can get married in three days."
    },
    {
        "show_id": "s39",
        "type": "TV Show",
        "title": "à¹à",
        "director": "",
        "cast": "Chutavuth Pattarakampol, Sheranut Yusananda, Nichaphat Chatchaipholrat, Thassapak Hsu",
        "country": "",
        "date_added": "March 30, 2019",
        "release_year": "2016",
        "rating": "TV-14",
        "duration": "1 Season",
        "listed_in": "International TV Shows, Romantic TV Shows, TV Comedies",
        "description": "When two brothers fall for two sisters, they quickly realize the age differences between them are too big to ignore."
    },
    {
        "show_id": "s40",
        "type": "Movie",
        "title": "Â¡Ay, mi madre!",
        "director": "Frank Ariza",
        "cast": "EstefanÃ­a de los Santos, Secun de la Rosa, Terele PÃ¡vez, MarÃ­a Alfonsa Rosso, Mariola Fuentes, Alfonso SÃ¡nchez, Paz Vega, Marta TornÃ©, Concha GalÃ¡n",
        "country": "Spain",
        "date_added": "July 19, 2019",
        "release_year": "2019",
        "rating": "TV-MA",
        "duration": "81 min",
        "listed_in": "Comedies, International Movies",
        "description": "When her estranged mother suddenly dies, a woman must follow the quirky instructions laid out in the will in order to collect an important inheritance."
    },
    {
        "show_id": "s41",
        "type": "Movie",
        "title": "Ãarsi Pazar",
        "director": "Muharrem GÃ¼lmez",
        "cast": "Erdem Yener, Ayhan TaÅ, Emin Olcay, Muharrem GÃ¼lmez, Elif Nur KerkÃ¼k, TarÄ±k PapuÃ§Ã§uoÄlu, Suzan Aksoy, DoÄa KonakoÄlu, Esin Eden, Deniz Ãzerman",
        "country": "Turkey",
        "date_added": "March 10, 2017",
        "release_year": "2015",
        "rating": "TV-14",
        "duration": "97 min",
        "listed_in": "Comedies, International Movies",
        "description": "The slacker owner of a public bath house rallies his community to save it when a big developer comes to town to close it down and open a new mall."
    },
]